name: netflix workflow

on: 
    workflow_dispatch:


jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            # step 1
            - name: checkout code
              uses: actions/checkout@v7.0.1

            # step 2
            - name: setup node
              uses: actions/setup-node@v7.0.0
              with:
                node-version: 24
              
            #step 3
            - name: install dependencies
              run: npm install

            #step 4
            - name: build
              run: |
                npm run build

                if [ -d "dist" ]; then 
                    echo "dist exist"

                else 
                    echo "directory does not exist!!"
                    exit 1
                fi  

            #step 5 
            - name: cmd
              run: pwd

            #step 6
            - name: aws login
              uses: aws-actions/configure-aws-credentials@v6.2.2
              with: 
                role-to-assume: arn:aws:iam::987020212550:role/s3-access
                aws-region: ap-south-1

            #step 7                
            - name: s3 check
              run: aws s3 sync --delete  ./dist/ s3://demo-bucket-web-com

